version: "3.9"

services:
  mongo_db:
    container_name: mongo_db
    image: mongo
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 50s
    ports:
      - 27018:27017
    command: mongod
    env_file: ./mongo_db/.env
    volumes:
      - ./mongo_db/data:/data/db
      #- ./mongo_db/import:/tmp/import #si option 1 : import de données, sinon supprimer ou laisser cette ligne en commentaire
      #- ./mongo_db/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh #si option 1 ou 2 : initialisation de la base de données + import ou création, sinon supprimer ou laisser cette ligne en commentaire
    networks:
      - mdb

  mongo-express:
    container_name: mongo_express
    image: mongo-express
    ports:
      - 8081:8081
    env_file: ./mongo_db/.env
    depends_on:
      mongo_db:
        condition: service_healthy
    networks:
      - mdb

networks:
  mdb:
    driver: bridge
